[package]
name = "circt-sys"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
doctest = false

[dependencies]
cmake = "0.1.49"
libc = "*"
num_cpus = "1.15.0"

[build-dependencies]
bindgen = "*"
cargo-emit = "0.2.1"
cc = "*"
cmake = "0.1.49"
glob = "0.3.1"
num_cpus = "1.15.0"

[features]
