#ifndef CXX_WRAPPER__H
#define CXX_WRAPPER__H

#define NDEBUG 1

#include "mlir/Conversion/Passes.h"
#include "mlir/Transforms/Passes.h"

#include "circt/Conversion/Passes.h"
#include "circt/Transforms/Passes.h"
#include "circt/Dialect/FIRRTL/Passes.h"
#include "circt/Dialect/Seq/SeqPasses.h"
#include "circt/Dialect/HW/HWPasses.h"
#include "circt/Dialect/Pipeline/PipelinePasses.h"
#include "circt/Dialect/Handshake/HandshakePasses.h"
#include "circt/Dialect/FSM/FSMPasses.h"
#include "circt/Dialect/SV/SVPasses.h"

// // #include "mlir/IR/Diagnostics.h"
// // #include "mlir/IR/Location.h"
// #include "mlir/IR/MLIRContext.h"
// #include "mlir/IR/Dialect.h"
// // #include "mlir/IR/DialectInterface.h"
// // #include "mlir/IR/DialectImplementation.h"
// // #include "mlir/IR/BuiltinDialect.h"
// // #include "mlir/IR/AttributeSupport.h"
// // #include "mlir/IR/Attributes.h"
// // #include "mlir/IR/BuiltinAttributes.h"
// // #include "mlir/IR/BuiltinOps.h"
// // #include "mlir/IR/IRMapping.h"
// // #include "mlir/IR/IntegerSet.h"
// // #include "mlir/IR/OpDefinition.h"
// // #include "mlir/IR/OpImplementation.h"
// // #include "mlir/IR/Operation.h"
// // #include "mlir/IR/OperationSupport.h"
// // #include "mlir/IR/OwningOpRef.h"
// // #include "mlir/IR/SymbolTable.h"
// // #include "mlir/IR/Region.h"
// // #include "mlir/IR/Block.h"
// // #include "mlir/IR/Types.h"
// // #include "mlir/IR/Value.h"
// // #include "mlir/IR/Verifier.h"
// // #include "mlir/Pass/Pass.h"
// // #include "mlir/Pass/PassManager.h"
// // #include "mlir/Pass/PassRegistry.h"
// // #include "circt/Dialect/FIRRTL/CHIRRTLDialect.h"
// // #include "circt/Dialect/FIRRTL/FIRParser.h"
// // #include "circt/Dialect/FIRRTL/FIRRTLDialect.h"
// // #include "circt/Dialect/FIRRTL/FIRRTLOps.h"
// // #include "circt/Conversion/ExportVerilog.h"
// // #include "circt/Dialect/Comb/CombDialect.h"
// #include "circt/Dialect/Comb/CombOps.h"
// // #include "circt/Dialect/Comb/CombVisitors.h"
// // #include "circt/Dialect/Seq/SeqDialect.h"
// // #include "circt/Dialect/Seq/SeqOpInterfaces.h"
// // #include "circt/Dialect/Seq/SeqTypes.h"
// #include "circt/Dialect/Seq/SeqOps.h"
// #include "circt/Dialect/HW/HWAttributes.h"
// #include "circt/Dialect/HW/HWDialect.h"
// #include "circt/Dialect/HW/HWTypes.h"
// #include "circt/Dialect/HW/HWOps.h"
// // #include "circt/Dialect/HW/ModuleImplementation.h"
// // #include "circt/Dialect/HW/Namespace.h"


#endif // CXX_WRAPPER__H